2021-08-24 11:36:25 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
2021-08-24 11:36:25 0 [Note] InnoDB: Number of pools: 1
2021-08-24 11:36:25 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
2021-08-24 11:36:25 0 [Note] InnoDB: Initializing buffer pool, total size = 2147483648, chunk size = 134217728
2021-08-24 11:36:25 0 [Note] InnoDB: Completed initialization of buffer pool
2021-08-24 11:36:25 0 [Note] InnoDB: 128 rollback segments are active.
2021-08-24 11:36:25 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2021-08-24 11:36:25 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2021-08-24 11:36:25 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2021-08-24 11:36:25 0 [Note] InnoDB: 10.6.4 started; log sequence number 42161; transaction id 14
2021-08-24 11:36:25 0 [Note] Plugin 'FEEDBACK' is disabled.
2021-08-24 11:36:25 0 [Note] InnoDB: Loading buffer pool(s) from D:\Programme\learn_coding\Selenium\Insta_Bot\Code\data\data\ib_buffer_pool
2021-08-24 11:36:25 0 [Note] Server socket created on IP: '::'.
2021-08-24 11:36:25 0 [Note] Server socket created on IP: '0.0.0.0'.
2021-08-24 11:36:25 0 [Note] InnoDB: Buffer pool(s) load completed at 210824 11:36:25
2021-08-24 11:36:25 0 [Note] D:\Programme\learn_coding\Selenium\Insta_Bot\Code\data\bin\mysqld.exe: ready for connections.
Version: '10.6.4-MariaDB'  socket: ''  port: 3306  mariadb.org binary distribution
2021-08-24 13:04:03 3 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2021-08-24 13:04:26 4 [Warning] Access denied for user 'Jan_Lokal'@'localhost' (using password: NO)
2021-08-24 13:05:03 5 [Warning] Access denied for user 'Jan_Lokal'@'localhost' (using password: NO)
2021-08-24 13:05:15 6 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2021-08-25  1:03:30 7 [Warning] Aborted connection 7 to db: 'instabot' user: 'root' host: 'localhost' (Got an error reading communication packets)
2021-08-25 18:09:25 32 [Warning] Aborted connection 32 to db: 'instabot' user: 'root' host: 'localhost' (Got an error reading communication packets)
